In [ ]:
import numpy as np
import pandas as pd
%cd /Users/kevjangs/Desktop/cs-ai-quant/cs-ai-quant-roadmap/week01/titanic_forecast
%load_ext autoreload

[Errno 2] No such file or directory: '/Users/kevjangs/Desktop/cs-ai-quant/cs-ai-quant-roadmap/week01/titanic_forecast'
/Users/kevjangs/Desktop/cs-ai-quant/ca-ai-quant-roadmap/week01/titanic_forecast
The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [ ]:
%autoreload 2

test = pd.read_csv('data/test.csv')
train = pd.read_csv('data/train.csv')

In [16]:
test.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [15]:
#baseline model Random Forest
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split    
from sklearn.preprocessing import LabelEncoder
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

features = ['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Embarked']

X = pd.get_dummies(train[features],dtype=int)
Y = train['Survived']

X_train , X_valid , Y_train , Y_valid = train_test_split(X,Y, test_size=0.2, random_state=62)

model = RandomForestClassifier(n_estimators=100, random_state=62)
model.fit(X_train, Y_train)
valid_preds = model.predict(X_valid)
valid_acc = accuracy_score(Y_valid, valid_preds)

print(f"valid_acc is {valid_acc}")

X_test = pd.get_dummies(test[features],dtype=int)
test_preds = model.predict(X_test)
baseline_submission =pd.DataFrame({'passengerId':test['PassengerId'], 'Survived':test_preds})
baseline_submission.to_csv("data/baseline_submission.csv", index=False)
baseline_submission.head()

valid_acc is 0.8156424581005587

   passengerId  Survived
0          892         0
1          893         0
2          894         0
3          895         0
4          896         1

In [10]:
features = ['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Cabin', 'Embarked']
for col in train[features].columns:
    print(f"feature is {col}")
    print(col, train[col].isnull().sum())
    print(train[col].unique())

feature is Pclass
Pclass 0
[3 1 2]
feature is Sex
Sex 0
<StringArray>
['male', 'female']
Length: 2, dtype: str
feature is Age
Age 177
[22.   38.   26.   35.     nan 54.    2.   27.   14.    4.   58.   20.
 39.   55.   31.   34.   15.   28.    8.   19.   40.   66.   42.   21.
 18.    3.    7.   49.   29.   65.   28.5   5.   11.   45.   17.   32.
 16.   25.    0.83 30.   33.   23.   24.   46.   59.   71.   37.   47.
 14.5  70.5  32.5  12.    9.   36.5  51.   55.5  40.5  44.    1.   61.
 56.   50.   36.   45.5  20.5  62.   41.   52.   63.   23.5   0.92 43.
 60.   10.   64.   13.   48.    0.75 53.   57.   80.   70.   24.5   6.
  0.67 30.5   0.42 34.5  74.  ]
feature is SibSp
SibSp 0
[1 0 3 4 2 5 8]
feature is Parch
Parch 0
[0 1 2 5 3 4 6]
feature is Fare
Fare 0
[  7.25    71.2833   7.925   53.1      8.05     8.4583  51.8625  21.075
  11.1333  30.0708  16.7     26.55    31.275    7.8542  16.      29.125
  13.      18.       7.225   26.       8.0292  35.5     31.3875 263.
   7.8792   7.8958  27.7208 146.5208   7.75    10.5     82.1708  52.
   7.2292  11.2417   9.475   21.      41.5792  15.5     21.6792  17.8
  39.6875   7.8     76.7292  61.9792  27.75    46.9     80.      83.475
  27.9     15.2458   8.1583   8.6625  73.5     14.4542  56.4958   7.65
  29.      12.475    9.       9.5      7.7875  47.1     15.85    34.375
  61.175   20.575   34.6542  63.3583  23.      77.2875   8.6542   7.775
  24.15     9.825   14.4583 247.5208   7.1417  22.3583   6.975    7.05
  14.5     15.0458  26.2833   9.2167  79.2      6.75    11.5     36.75
   7.7958  12.525   66.6      7.3125  61.3792   7.7333  69.55    16.1
  15.75    20.525   55.      25.925   33.5     30.6958  25.4667  28.7125
   0.      15.05    39.      22.025   50.       8.4042   6.4958  10.4625
  18.7875  31.     113.275   27.      76.2917  90.       9.35    13.5
   7.55    26.25    12.275    7.125   52.5542  20.2125  86.5    512.3292
  79.65   153.4625 135.6333  19.5     29.7     77.9583  20.25    78.85
  91.0792  12.875    8.85   151.55    30.5     23.25    12.35   110.8833
 108.9     24.      56.9292  83.1583 262.375   14.     164.8667 134.5
   6.2375  57.9792  28.5    133.65    15.9      9.225   35.      75.25
  69.3     55.4417 211.5      4.0125 227.525   15.7417   7.7292  12.
 120.      12.65    18.75     6.8583  32.5      7.875   14.4     55.9
   8.1125  81.8583  19.2583  19.9667  89.1042  38.5      7.725   13.7917
   9.8375   7.0458   7.5208  12.2875   9.5875  49.5042  78.2667  15.1
   7.6292  22.525   26.2875  59.4      7.4958  34.0208  93.5    221.7792
 106.425   49.5     71.      13.8625   7.8292  39.6     17.4     51.4792
  26.3875  30.      40.125    8.7125  15.      33.      42.4     15.55
  65.      32.3208   7.0542   8.4333  25.5875   9.8417   8.1375  10.1708
 211.3375  57.      13.4167   7.7417   9.4833   7.7375   8.3625  23.45
  25.9292   8.6833   8.5167   7.8875  37.0042   6.45     6.95     8.3
   6.4375  39.4     14.1083  13.8583  50.4958   5.       9.8458  10.5167]
feature is Cabin
Cabin 687
<StringArray>
[          nan,         'C85',        'C123',         'E46',          'G6',
        'C103',         'D56',          'A6', 'C23 C25 C27',         'B78',
 ...
        'B102',         'B69',         'E49',         'C47',         'D28',
         'E17',         'A24',         'C50',         'B42',        'C148']
Length: 148, dtype: str
feature is Embarked
Embarked 2
<StringArray>
['S', 'C', 'Q', nan]
Length: 4, dtype: str